[package]
name = "octopusmq"
version = "0.1.0"
edition = "2021"
description = "Fast distributed highly available in-memory key/value database with publish-subscribe interface"

[[bin]]
name = "server"
path = "src/server/main.rs"

[[bin]]
name = "client"
path = "src/client/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
